# TODO(mtwilliams): Setup Postgres.
sudo: false
language: elixir
elixir:
  - 1.4
otp_release:
  - 19
env:
  global:
    - NODE_ENV=development
before_install:
  - mix local.hex --force
  - mix local.rebar --force
install:
  - mix do deps.get
script:
  - mix deps.compile --all, compile
  - mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    recipients:
      - m.t.williams@live.com
    on_success: change
    on_failure: change
