svc:
  build: .
  environment:
    - DOCKER=1
    - MIX_ENV=dev
    - DATABASE_URL=postgres://walter:d88ewHcWIKRfHDDHPt95FDRXwZgVaEpw@postgres:5432/lwnqegbfsm24w2sq
  volumes:
    - ./:/app
  ports:
    - 4000:4000
    - 4001:4001
  links:
    - db:postgres

db:
  image: paperstash/db:9.4.1
  environment:
    - DB_NAME=e8uuvoq6wybl3tes
    - DB_USER=paperstash
    - DB_PASSWORD=gJ4c5x0rPJUzQUSHtszweLpW2PeER0Kv
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432:5432
